In [4]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

print("=== 1. СОЗДАНИЕ МАССИВОВ ===")

# 2. Примеры создания массивов из обычных списков
list_array = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", list_array)

# Создание массивов с использованием функций zeros, ones, arange
zeros_array = np.zeros(5)  # Массив из 5 нулей
ones_array = np.ones(3)    # Массив из 3 единиц
range_array = np.arange(0, 10, 2)  # Числа от 0 до 10 с шагом 2

print("Нулевой массив:", zeros_array)
print("Массив из единиц:", ones_array)
print("Массив с диапазоном:", range_array)

print("\n=== 2. ДЕМОНСТРАЦИЯ АТРИБУТОВ ===")
# 3. Демонстрация атрибутов массива
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив:")
print(matrix)

# Вывод формы (shape) и типа данных (dtype)
print("Форма массива (shape):", matrix.shape)
print("Тип данных (dtype):", matrix.dtype)

print("\n=== 3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===")
# 4. Примеры индексирования и срезов
# Получение отдельного элемента
print("Элемент [1,2]:", matrix[1, 2])  # Вторая строка, третий элемент

# Извлечение подмассива с помощью среза
print("Первые две строки:")
print(matrix[0:2, :])  # Первые две строки, все столбцы
print("Последние два столбца:")
print(matrix[:, 1:])   # Все строки, столбцы с 1 до конца

print("\n=== 4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===")
# 5. Примеры векторных операций и базовых статистик
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементное сложение и умножение массивов
print("Массив a:", a)
print("Массив b:", b)
print("Поэлементное сложение (a + b):", a + b)
print("Поэлементное умножение (a * b):", a * b)

# Вычисление статистики
print("Среднее значение массива a:", np.mean(a))
print("Сумма всех элементов b:", np.sum(b))
print("Максимальное значение в a:", np.max(a))
print("Минимальное значение в b:", np.min(b))

=== 1. СОЗДАНИЕ МАССИВОВ ===
Массив из списка: [1 2 3 4 5]
Нулевой массив: [0. 0. 0. 0. 0.]
Массив из единиц: [1. 1. 1.]
Массив с диапазоном: [0 2 4 6 8]

=== 2. ДЕМОНСТРАЦИЯ АТРИБУТОВ ===
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма массива (shape): (3, 3)
Тип данных (dtype): int64

=== 3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===
Элемент [1,2]: 6
Первые две строки:
[[1 2 3]
 [4 5 6]]
Последние два столбца:
[[2 3]
 [5 6]
 [8 9]]

=== 4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===
Массив a: [1 2 3]
Массив b: [4 5 6]
Поэлементное сложение (a + b): [5 7 9]
Поэлементное умножение (a * b): [ 4 10 18]
Среднее значение массива a: 2.0
Сумма всех элементов b: 15
Максимальное значение в a: 3
Минимальное значение в b: 4
